# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# USWDS Settings
# https://github.com/usds/website/blob/master/_config.yml

title: GovA11y Glossary
email: hello@gova11y.io
description: >- # this means to ignore newlines until "baseurl:"
    Terms, definitions, & equations used to define accessibility, government, etc...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glossary.gova11y.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: GovA11y

# This custom var is used only in meta tags in _head.html. It does not break sites for staging, dev, etc.
domain: "docs.gova11y.io"

timezone: "America/New_York"
social_image: social-card--default.png

collections:
    projects:
        output: false
    a11yrithms:
        output: true
        permalink: /:collection/:path/

# Build settings
theme: uswds-jekyll
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from

# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag
twitter:
    username: civicactions
logo: /img/usds-logo-onwhite.png
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
